### ISSUE TITLE
interferes with other uses of timecop

### ISSUE THREAD

**Issue by michaelkirk** [ferndopolis/timecop-console#2]
I'm requiring timecop_console, but not using, it in my cucumber integration tests.

I'm using Timecop explicity in some of my cucumber steps, but finding that Time.now is reset to "real" time after the next request, I suspect because of this:

https://github.com/jtrupiano/timecop-console/blob/master/lib/timecop_console/controller_methods.rb#L17

Why are we calling Timecop.return every request? Why not _just_ when someone explicity TimecopConsole::MainController#resets ?
https://github.com/jtrupiano/timecop-console/blob/master/app/controllers/timecop_console/main_controller.rb#L27

I suspect this is more complicated because you are trying to have a Timecop offset per user session. Is that right? Any ideas of how to reconcile these?

**Comment by nfedyashev** [comment]
Hi @michaelkirk!

Probably the simplest way would be to avoid requiring `timecop_console` in cucumber integration tests.
You can do so by excluding `timecop_console` dependency(if you have one) from `cucumber` group of Gemfile,

Or by requiring having `timecop_console` as part of only those group/groups where you actually need it(development?)

Please ping me if this problem persists
